"""
PLCD Testing Assistant - Feedback Collection Tool (Sequential Version)
Allows testers to correct selectors with context awareness
"""

import sys
import json
import logging
from pathlib import Path
from typing import Dict, List, Any, Optional
from datetime import datetime

from config_loader import load_config, get_azure_client, get_chroma_client

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('Logs/feedback_taseq.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


class FeedbackToolSeq:
    """
    Feedback collection tool with context awareness
    """

    def __init__(self, config: Dict[str, Any]):
        """
        Initialize feedback tool

        Args:
            config: Configuration dictionary
        """
        self.config = config
        self.azure_client = get_azure_client(config)
        self.chroma_client = get_chroma_client(config)

        # Get learning collection
        collection_name = config.get('vector_database', {}).get('collections', {}).get('runtime_learned', 'learning_collection')
        self.learning_collection = self.chroma_client.get_or_create_collection(name=collection_name)

        logger.info("Feedback Tool (Sequential) initialized")

    def process_report(self, report_path: str):
        """
        Process HTML report and collect feedback

        Args:
            report_path: Path to HTML report
        """
        print("\n" + "=" * 80)
        print(f"PLCD Feedback Tool - Processing Report")
        print("=" * 80)

        # Read context trace JSON (generated by plcd_taseq.py)
        context_trace_path = self._find_context_trace(report_path)

        if not context_trace_path:
            print("[ERROR] Could not find context trace JSON file")
            print("Make sure the test was run with plcd_taseq.py")
            return

        # Load context trace
        with open(context_trace_path, 'r', encoding='utf-8') as f:
            trace_data = json.load(f)

        ticket_id = trace_data.get('ticket_id', 'Unknown')
        context_history = trace_data.get('context_history', [])
        agent_chain = trace_data.get('agent_chain', [])

        print(f"\n[OK] Loaded context trace for: {ticket_id}")
        print(f"[OK] Context history: {len(context_history)} steps")
        print(f"[OK] Agent chain: {' -> '.join(agent_chain)}")

        # Parse HTML report to get step results
        step_results = self._parse_html_report(report_path)

        if not step_results:
            print("[ERROR] No step results found in report")
            return

        print(f"\n[OK] Found {len(step_results)} test steps")

        # Show failed steps
        failed_steps = [s for s in step_results if s.get('status') == 'FAILED']

        if not failed_steps:
            print("\n[INFO] No failed steps found. All steps passed!")
            return

        print(f"\n[INFO] Found {len(failed_steps)} failed steps")
        print("-" * 80)

        # Collect corrections for failed steps
        corrections = []

        for step in failed_steps:
            step_num = step.get('step_number', 0)
            step_text = step.get('step_text', '')
            tried_selector = step.get('selector', 'None')
            error = step.get('error', 'Unknown error')

            # Get context for this step
            step_context = context_history[step_num - 1] if step_num <= len(context_history) else {}

            print(f"\nStep {step_num}: {step_text}")
            print(f"Status: FAILED")
            print(f"Tried selector: {tried_selector}")
            print(f"Error: {error}")
            print(f"\nContext:")
            print(f"  URL: {step_context.get('url', 'Unknown')}")
            print(f"  Visible elements: {len(step_context.get('visible_elements', []))} data-* attributes")

            # Ask for correction
            print("\n" + "-" * 40)
            correct_selector = input("Enter correct selector (or press Enter to skip): ").strip()

            if correct_selector:
                # Ask for context tags
                print("\nAdd context tags to help identify similar situations:")
                print("Examples: navigation, from_dashboard, after_login, table_action")
                context_tags = input("Context tags (comma-separated, or press Enter to skip): ").strip()

                tags = [t.strip() for t in context_tags.split(',')] if context_tags else []

                correction = {
                    'step_number': step_num,
                    'step_text': step_text,
                    'wrong_selector': tried_selector,
                    'correct_selector': correct_selector,
                    'context': step_context,
                    'context_tags': tags,
                    'ticket_id': ticket_id
                }

                corrections.append(correction)
                print(f"[OK] Correction recorded")
            else:
                print("[SKIP] Skipping this step")

            print("-" * 40)

        # Store corrections to learning collection
        if corrections:
            print(f"\n[INFO] Storing {len(corrections)} corrections to learning collection...")

            for correction in corrections:
                self._store_correction(correction)

            print(f"[OK] All corrections stored successfully")
            print(f"\n[INFO] These corrections will be used in future test runs")

        print("\n" + "=" * 80)
        print("Feedback Collection Complete!")
        print("=" * 80)

    def _find_context_trace(self, report_path: str) -> Optional[str]:
        """Find corresponding context trace JSON file"""
        report_path_obj = Path(report_path)
        ticket_id = report_path_obj.stem.split('_')[0]  # Extract ticket ID

        # Look for context trace in Logs folder
        logs_folder = Path(self.config['folders']['logs'])
        pattern = f"context_trace_{ticket_id}_*.json"

        matching_files = list(logs_folder.glob(pattern))

        if matching_files:
            # Return most recent
            return str(sorted(matching_files, key=lambda p: p.stat().st_mtime, reverse=True)[0])

        return None

    def _parse_html_report(self, report_path: str) -> List[Dict[str, Any]]:
        """Parse HTML report to extract step results"""
        from bs4 import BeautifulSoup

        try:
            with open(report_path, 'r', encoding='utf-8') as f:
                html_content = f.read()

            soup = BeautifulSoup(html_content, 'html.parser')

            step_results = []

            # Find step table
            step_table = soup.find('table', class_='step-table')
            if step_table:
                rows = step_table.find('tbody').find_all('tr')

                for row in rows:
                    cols = row.find_all('td')
                    if len(cols) >= 6:
                        step_num = int(cols[0].get_text().strip())
                        step_text = cols[1].get_text().strip()
                        selector_elem = cols[2].find('span', class_='selector')
                        selector = selector_elem.get_text().strip() if selector_elem else 'None'
                        status_elem = cols[5].find('span', class_='badge')
                        status = status_elem.get_text().strip() if status_elem else 'UNKNOWN'

                        step_results.append({
                            'step_number': step_num,
                            'step_text': step_text,
                            'selector': selector,
                            'status': status
                        })

            return step_results

        except Exception as e:
            logger.error(f"Failed to parse HTML report: {e}")
            return []

    def _store_correction(self, correction: Dict[str, Any]):
        """Store correction to learning collection"""
        try:
            step_text = correction['step_text']
            correct_selector = correction['correct_selector']
            context = correction['context']
            tags = correction['context_tags']

            # Generate unique ID
            import hashlib
            id_str = f"human_correction_{correction['ticket_id']}_{step_text}_{correct_selector}"
            doc_id = hashlib.md5(id_str.encode()).hexdigest()

            # Build document text with context
            url = context.get('url', '')
            visible = context.get('visible_elements', [])[:10]
            tags_str = ', '.join(tags) if tags else 'none'

            doc_text = f"{step_text} | URL: {url} | Selector: {correct_selector} | Tags: {tags_str} | Visible: {', '.join(visible)}"

            # Generate embedding
            response = self.azure_client.embeddings.create(
                input=doc_text,
                model=self.config['azure_openai']['models']['embedding']
            )
            embedding = response.data[0].embedding

            # Store to ChromaDB
            self.learning_collection.add(
                ids=[doc_id],
                embeddings=[embedding],
                documents=[doc_text],
                metadatas=[{
                    'step_text': step_text,
                    'selector': correct_selector,
                    'url_pattern': url,
                    'context_tags': ','.join(tags),
                    'wrong_selector': correction['wrong_selector'],
                    'confidence': 0.98,  # High confidence for human corrections
                    'source': 'human_feedback',
                    'verified': True,
                    'ticket_id': correction['ticket_id'],
                    'timestamp': datetime.now().isoformat()
                }]
            )

            logger.info(f"Stored human correction for '{step_text}'")

        except Exception as e:
            logger.error(f"Failed to store correction: {e}")


def main():
    """Main entry point"""

    if len(sys.argv) < 2:
        print("Usage: python feedback_taseq.py <REPORT_PATH>")
        print("Example: python feedback_taseq.py Reports\\RBPLCD-8835_20251118_164147_report.html")
        sys.exit(1)

    report_path = sys.argv[1]

    if not Path(report_path).exists():
        print(f"[ERROR] Report file not found: {report_path}")
        sys.exit(1)

    try:
        # Load configuration
        config = load_config()

        # Initialize feedback tool
        tool = FeedbackToolSeq(config)

        # Process report
        tool.process_report(report_path)

    except Exception as e:
        print(f"\n[ERROR] Fatal error: {e}")
        logger.error(f"Fatal error: {e}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
